### ISSUE TITLE
radiks CreateBlock fails with a type error

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/stackit#4]
1, Start Stackit.
2. Create a block to open a dialog
3. Enter the block data.
4. Press Create block to return to the dashbard
    A block row appears in the `radiks-server`  database in the mongdob.
5. The dashboard returns this error:

![image](https://user-images.githubusercontent.com/1347209/67038826-09862f80-f0d5-11e9-80a7-eb7e2a1b5f2c.png)

**Comment by moxiegirl** [comment]
@yknl Here is the error I am seeing.  The code that is throwing the error seems to be `BlockAd` in `Profile.js`

**Comment by friedger** [comment]
The user is not created correctly on radiks on signin

**Comment by moxiegirl** [comment]
@friedger Thanks for the PR! Saw it after this comment. I'll give that a try.

**Comment by friedger** [comment]
This should be fixed by #7

**Comment by moxiegirl** [comment]
Filed on Radiks here: https://github.com/blockstack-radiks/radiks-server/issues/26
